<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/

return [

    /*
     * Set trusted proxy IP addresses.
     *
     * Both IPv4 and IPv6 addresses are
     * supported, along with CIDR notation.
     *
     * The "*" character is syntactic sugar
     * within TrustedProxy to trust any proxy
     * that connects directly to your server,
     * a requirement when you cannot know the address
     * of your proxy (e.g. if using ELB or similar).
     *
     * The "**" character is syntactic sugar within
     * TrustedProxy to trust not just any proxy that
     * connects directly to your server, but also
     * proxies that connect to those proxies, and all
     * the way back until you reach the original source
     * IP. It will mean that $request->getClientIp()
     * always gets the originating client IP, no matter
     * how many proxies that client's request has
     * subsequently passed through.
     */
    'proxies' => env('APP_TRUSTED_PROXIES') !== null ?
        explode(',', env('APP_TRUSTED_PROXIES')) : '*',

    /*
     * To trust one or more specific proxies that connect
     * directly to your server, use an array of IP addresses:
     */
    // 'proxies' => ['192.168.1.1'],

    /*
     * Or, to trust all proxies that connect
     * directly to your server, use a "*"
     */
    // 'proxies' => '*',

    /*
     * Which headers to use to detect proxy-related data (For, Host, Proto, Port).
     *
     * This key is intentionally not set here. app/Http/Middleware/TrustProxies.php
     * already sets $headers on the middleware itself as a bitmask of the individual
     * Illuminate\Http\Request::HEADER_X_FORWARDED_* constants (FOR, HOST, PORT,
     * PROTO, AWS_ELB), which is what runtime uses. Prior versions of this file
     * carried a commented-out example referencing HEADER_X_FORWARDED_ALL, but that
     * constant was removed from Symfony (see symfony/symfony#38928) and uncommenting
     * it produced a fatal "Undefined constant" error. See #6852.
     *
     * If you need to change which forwarded headers are trusted, edit the $headers
     * property on App\Http\Middleware\TrustProxies rather than adding a 'headers'
     * key here.
     *
     * @link https://symfony.com/doc/current/deployment/proxies.html
     */

];
